[phases.setup]
nixPkgs = ["nginx", "php81", "php81Packages.php-fpm"]

[phases.build]
cmds = [
    "echo 'upload_max_filesize = 30M' >> /etc/php/8.1/fpm/php.ini",
    "echo 'post_max_size = 35M' >> /etc/php/8.1/fpm/php.ini",
    "echo 'client_max_body_size 35M;' > /etc/nginx/conf.d/custom.conf"
]

[phases.start]
cmds = [
    "php-fpm -y /etc/php/8.1/fpm/php-fpm.conf",
    "nginx -g 'daemon off;'"
]

[staticAssets]
"nginx.conf" = '''
worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    server {
        listen 80;
        server_name localhost;

        root /app;
        index index.php;

        location / {
            try_files $uri $uri/ /index.php?$query_string;
        }

        location ~ \.php$ {
            include fastcgi_params;
            fastcgi_pass 127.0.0.1:9000;
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        }

        client_max_body_size 35M;
    }
}
'''
